// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MasoudHeydari/eps-api/ent/searchquery"
	"github.com/MasoudHeydari/eps-api/ent/serp"
	"github.com/google/uuid"
)

// SearchQueryCreate is the builder for creating a SearchQuery entity.
type SearchQueryCreate struct {
	config
	mutation *SearchQueryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQuery sets the "query" field.
func (sqc *SearchQueryCreate) SetQuery(s string) *SearchQueryCreate {
	sqc.mutation.SetQuery(s)
	return sqc
}

// SetLocCode sets the "loc_code" field.
func (sqc *SearchQueryCreate) SetLocCode(i int) *SearchQueryCreate {
	sqc.mutation.SetLocCode(i)
	return sqc
}

// SetLanguage sets the "language" field.
func (sqc *SearchQueryCreate) SetLanguage(s string) *SearchQueryCreate {
	sqc.mutation.SetLanguage(s)
	return sqc
}

// SetJobID sets the "job_id" field.
func (sqc *SearchQueryCreate) SetJobID(u uuid.UUID) *SearchQueryCreate {
	sqc.mutation.SetJobID(u)
	return sqc
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (sqc *SearchQueryCreate) SetNillableJobID(u *uuid.UUID) *SearchQueryCreate {
	if u != nil {
		sqc.SetJobID(*u)
	}
	return sqc
}

// SetIsFinished sets the "is_finished" field.
func (sqc *SearchQueryCreate) SetIsFinished(b bool) *SearchQueryCreate {
	sqc.mutation.SetIsFinished(b)
	return sqc
}

// SetNillableIsFinished sets the "is_finished" field if the given value is not nil.
func (sqc *SearchQueryCreate) SetNillableIsFinished(b *bool) *SearchQueryCreate {
	if b != nil {
		sqc.SetIsFinished(*b)
	}
	return sqc
}

// SetCreatedAt sets the "created_at" field.
func (sqc *SearchQueryCreate) SetCreatedAt(t time.Time) *SearchQueryCreate {
	sqc.mutation.SetCreatedAt(t)
	return sqc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sqc *SearchQueryCreate) SetNillableCreatedAt(t *time.Time) *SearchQueryCreate {
	if t != nil {
		sqc.SetCreatedAt(*t)
	}
	return sqc
}

// AddSerpIDs adds the "serps" edge to the SERP entity by IDs.
func (sqc *SearchQueryCreate) AddSerpIDs(ids ...int) *SearchQueryCreate {
	sqc.mutation.AddSerpIDs(ids...)
	return sqc
}

// AddSerps adds the "serps" edges to the SERP entity.
func (sqc *SearchQueryCreate) AddSerps(s ...*SERP) *SearchQueryCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sqc.AddSerpIDs(ids...)
}

// Mutation returns the SearchQueryMutation object of the builder.
func (sqc *SearchQueryCreate) Mutation() *SearchQueryMutation {
	return sqc.mutation
}

// Save creates the SearchQuery in the database.
func (sqc *SearchQueryCreate) Save(ctx context.Context) (*SearchQuery, error) {
	sqc.defaults()
	return withHooks(ctx, sqc.sqlSave, sqc.mutation, sqc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sqc *SearchQueryCreate) SaveX(ctx context.Context) *SearchQuery {
	v, err := sqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sqc *SearchQueryCreate) Exec(ctx context.Context) error {
	_, err := sqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sqc *SearchQueryCreate) ExecX(ctx context.Context) {
	if err := sqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sqc *SearchQueryCreate) defaults() {
	if _, ok := sqc.mutation.IsFinished(); !ok {
		v := searchquery.DefaultIsFinished
		sqc.mutation.SetIsFinished(v)
	}
	if _, ok := sqc.mutation.CreatedAt(); !ok {
		v := searchquery.DefaultCreatedAt()
		sqc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sqc *SearchQueryCreate) check() error {
	if _, ok := sqc.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "SearchQuery.query"`)}
	}
	if v, ok := sqc.mutation.Query(); ok {
		if err := searchquery.QueryValidator(v); err != nil {
			return &ValidationError{Name: "query", err: fmt.Errorf(`ent: validator failed for field "SearchQuery.query": %w`, err)}
		}
	}
	if _, ok := sqc.mutation.LocCode(); !ok {
		return &ValidationError{Name: "loc_code", err: errors.New(`ent: missing required field "SearchQuery.loc_code"`)}
	}
	if _, ok := sqc.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "SearchQuery.language"`)}
	}
	if _, ok := sqc.mutation.IsFinished(); !ok {
		return &ValidationError{Name: "is_finished", err: errors.New(`ent: missing required field "SearchQuery.is_finished"`)}
	}
	if _, ok := sqc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SearchQuery.created_at"`)}
	}
	return nil
}

func (sqc *SearchQueryCreate) sqlSave(ctx context.Context) (*SearchQuery, error) {
	if err := sqc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sqc.mutation.id = &_node.ID
	sqc.mutation.done = true
	return _node, nil
}

func (sqc *SearchQueryCreate) createSpec() (*SearchQuery, *sqlgraph.CreateSpec) {
	var (
		_node = &SearchQuery{config: sqc.config}
		_spec = sqlgraph.NewCreateSpec(searchquery.Table, sqlgraph.NewFieldSpec(searchquery.FieldID, field.TypeInt))
	)
	_spec.OnConflict = sqc.conflict
	if value, ok := sqc.mutation.Query(); ok {
		_spec.SetField(searchquery.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := sqc.mutation.LocCode(); ok {
		_spec.SetField(searchquery.FieldLocCode, field.TypeInt, value)
		_node.LocCode = value
	}
	if value, ok := sqc.mutation.Language(); ok {
		_spec.SetField(searchquery.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := sqc.mutation.JobID(); ok {
		_spec.SetField(searchquery.FieldJobID, field.TypeUUID, value)
		_node.JobID = value
	}
	if value, ok := sqc.mutation.IsFinished(); ok {
		_spec.SetField(searchquery.FieldIsFinished, field.TypeBool, value)
		_node.IsFinished = value
	}
	if value, ok := sqc.mutation.CreatedAt(); ok {
		_spec.SetField(searchquery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := sqc.mutation.SerpsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   searchquery.SerpsTable,
			Columns: []string{searchquery.SerpsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(serp.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SearchQuery.Create().
//		SetQuery(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SearchQueryUpsert) {
//			SetQuery(v+v).
//		}).
//		Exec(ctx)
func (sqc *SearchQueryCreate) OnConflict(opts ...sql.ConflictOption) *SearchQueryUpsertOne {
	sqc.conflict = opts
	return &SearchQueryUpsertOne{
		create: sqc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SearchQuery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sqc *SearchQueryCreate) OnConflictColumns(columns ...string) *SearchQueryUpsertOne {
	sqc.conflict = append(sqc.conflict, sql.ConflictColumns(columns...))
	return &SearchQueryUpsertOne{
		create: sqc,
	}
}

type (
	// SearchQueryUpsertOne is the builder for "upsert"-ing
	//  one SearchQuery node.
	SearchQueryUpsertOne struct {
		create *SearchQueryCreate
	}

	// SearchQueryUpsert is the "OnConflict" setter.
	SearchQueryUpsert struct {
		*sql.UpdateSet
	}
)

// SetQuery sets the "query" field.
func (u *SearchQueryUpsert) SetQuery(v string) *SearchQueryUpsert {
	u.Set(searchquery.FieldQuery, v)
	return u
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *SearchQueryUpsert) UpdateQuery() *SearchQueryUpsert {
	u.SetExcluded(searchquery.FieldQuery)
	return u
}

// SetLocCode sets the "loc_code" field.
func (u *SearchQueryUpsert) SetLocCode(v int) *SearchQueryUpsert {
	u.Set(searchquery.FieldLocCode, v)
	return u
}

// UpdateLocCode sets the "loc_code" field to the value that was provided on create.
func (u *SearchQueryUpsert) UpdateLocCode() *SearchQueryUpsert {
	u.SetExcluded(searchquery.FieldLocCode)
	return u
}

// AddLocCode adds v to the "loc_code" field.
func (u *SearchQueryUpsert) AddLocCode(v int) *SearchQueryUpsert {
	u.Add(searchquery.FieldLocCode, v)
	return u
}

// SetLanguage sets the "language" field.
func (u *SearchQueryUpsert) SetLanguage(v string) *SearchQueryUpsert {
	u.Set(searchquery.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SearchQueryUpsert) UpdateLanguage() *SearchQueryUpsert {
	u.SetExcluded(searchquery.FieldLanguage)
	return u
}

// SetJobID sets the "job_id" field.
func (u *SearchQueryUpsert) SetJobID(v uuid.UUID) *SearchQueryUpsert {
	u.Set(searchquery.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *SearchQueryUpsert) UpdateJobID() *SearchQueryUpsert {
	u.SetExcluded(searchquery.FieldJobID)
	return u
}

// ClearJobID clears the value of the "job_id" field.
func (u *SearchQueryUpsert) ClearJobID() *SearchQueryUpsert {
	u.SetNull(searchquery.FieldJobID)
	return u
}

// SetIsFinished sets the "is_finished" field.
func (u *SearchQueryUpsert) SetIsFinished(v bool) *SearchQueryUpsert {
	u.Set(searchquery.FieldIsFinished, v)
	return u
}

// UpdateIsFinished sets the "is_finished" field to the value that was provided on create.
func (u *SearchQueryUpsert) UpdateIsFinished() *SearchQueryUpsert {
	u.SetExcluded(searchquery.FieldIsFinished)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SearchQueryUpsert) SetCreatedAt(v time.Time) *SearchQueryUpsert {
	u.Set(searchquery.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SearchQueryUpsert) UpdateCreatedAt() *SearchQueryUpsert {
	u.SetExcluded(searchquery.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SearchQuery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SearchQueryUpsertOne) UpdateNewValues() *SearchQueryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SearchQuery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SearchQueryUpsertOne) Ignore() *SearchQueryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SearchQueryUpsertOne) DoNothing() *SearchQueryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SearchQueryCreate.OnConflict
// documentation for more info.
func (u *SearchQueryUpsertOne) Update(set func(*SearchQueryUpsert)) *SearchQueryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SearchQueryUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuery sets the "query" field.
func (u *SearchQueryUpsertOne) SetQuery(v string) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *SearchQueryUpsertOne) UpdateQuery() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateQuery()
	})
}

// SetLocCode sets the "loc_code" field.
func (u *SearchQueryUpsertOne) SetLocCode(v int) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetLocCode(v)
	})
}

// AddLocCode adds v to the "loc_code" field.
func (u *SearchQueryUpsertOne) AddLocCode(v int) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.AddLocCode(v)
	})
}

// UpdateLocCode sets the "loc_code" field to the value that was provided on create.
func (u *SearchQueryUpsertOne) UpdateLocCode() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateLocCode()
	})
}

// SetLanguage sets the "language" field.
func (u *SearchQueryUpsertOne) SetLanguage(v string) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SearchQueryUpsertOne) UpdateLanguage() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateLanguage()
	})
}

// SetJobID sets the "job_id" field.
func (u *SearchQueryUpsertOne) SetJobID(v uuid.UUID) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *SearchQueryUpsertOne) UpdateJobID() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateJobID()
	})
}

// ClearJobID clears the value of the "job_id" field.
func (u *SearchQueryUpsertOne) ClearJobID() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.ClearJobID()
	})
}

// SetIsFinished sets the "is_finished" field.
func (u *SearchQueryUpsertOne) SetIsFinished(v bool) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetIsFinished(v)
	})
}

// UpdateIsFinished sets the "is_finished" field to the value that was provided on create.
func (u *SearchQueryUpsertOne) UpdateIsFinished() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateIsFinished()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SearchQueryUpsertOne) SetCreatedAt(v time.Time) *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SearchQueryUpsertOne) UpdateCreatedAt() *SearchQueryUpsertOne {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *SearchQueryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SearchQueryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SearchQueryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SearchQueryUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SearchQueryUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SearchQueryCreateBulk is the builder for creating many SearchQuery entities in bulk.
type SearchQueryCreateBulk struct {
	config
	err      error
	builders []*SearchQueryCreate
	conflict []sql.ConflictOption
}

// Save creates the SearchQuery entities in the database.
func (sqcb *SearchQueryCreateBulk) Save(ctx context.Context) ([]*SearchQuery, error) {
	if sqcb.err != nil {
		return nil, sqcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sqcb.builders))
	nodes := make([]*SearchQuery, len(sqcb.builders))
	mutators := make([]Mutator, len(sqcb.builders))
	for i := range sqcb.builders {
		func(i int, root context.Context) {
			builder := sqcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SearchQueryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sqcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sqcb *SearchQueryCreateBulk) SaveX(ctx context.Context) []*SearchQuery {
	v, err := sqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sqcb *SearchQueryCreateBulk) Exec(ctx context.Context) error {
	_, err := sqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sqcb *SearchQueryCreateBulk) ExecX(ctx context.Context) {
	if err := sqcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SearchQuery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SearchQueryUpsert) {
//			SetQuery(v+v).
//		}).
//		Exec(ctx)
func (sqcb *SearchQueryCreateBulk) OnConflict(opts ...sql.ConflictOption) *SearchQueryUpsertBulk {
	sqcb.conflict = opts
	return &SearchQueryUpsertBulk{
		create: sqcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SearchQuery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sqcb *SearchQueryCreateBulk) OnConflictColumns(columns ...string) *SearchQueryUpsertBulk {
	sqcb.conflict = append(sqcb.conflict, sql.ConflictColumns(columns...))
	return &SearchQueryUpsertBulk{
		create: sqcb,
	}
}

// SearchQueryUpsertBulk is the builder for "upsert"-ing
// a bulk of SearchQuery nodes.
type SearchQueryUpsertBulk struct {
	create *SearchQueryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SearchQuery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SearchQueryUpsertBulk) UpdateNewValues() *SearchQueryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SearchQuery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SearchQueryUpsertBulk) Ignore() *SearchQueryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SearchQueryUpsertBulk) DoNothing() *SearchQueryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SearchQueryCreateBulk.OnConflict
// documentation for more info.
func (u *SearchQueryUpsertBulk) Update(set func(*SearchQueryUpsert)) *SearchQueryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SearchQueryUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuery sets the "query" field.
func (u *SearchQueryUpsertBulk) SetQuery(v string) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *SearchQueryUpsertBulk) UpdateQuery() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateQuery()
	})
}

// SetLocCode sets the "loc_code" field.
func (u *SearchQueryUpsertBulk) SetLocCode(v int) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetLocCode(v)
	})
}

// AddLocCode adds v to the "loc_code" field.
func (u *SearchQueryUpsertBulk) AddLocCode(v int) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.AddLocCode(v)
	})
}

// UpdateLocCode sets the "loc_code" field to the value that was provided on create.
func (u *SearchQueryUpsertBulk) UpdateLocCode() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateLocCode()
	})
}

// SetLanguage sets the "language" field.
func (u *SearchQueryUpsertBulk) SetLanguage(v string) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SearchQueryUpsertBulk) UpdateLanguage() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateLanguage()
	})
}

// SetJobID sets the "job_id" field.
func (u *SearchQueryUpsertBulk) SetJobID(v uuid.UUID) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *SearchQueryUpsertBulk) UpdateJobID() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateJobID()
	})
}

// ClearJobID clears the value of the "job_id" field.
func (u *SearchQueryUpsertBulk) ClearJobID() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.ClearJobID()
	})
}

// SetIsFinished sets the "is_finished" field.
func (u *SearchQueryUpsertBulk) SetIsFinished(v bool) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetIsFinished(v)
	})
}

// UpdateIsFinished sets the "is_finished" field to the value that was provided on create.
func (u *SearchQueryUpsertBulk) UpdateIsFinished() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateIsFinished()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SearchQueryUpsertBulk) SetCreatedAt(v time.Time) *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SearchQueryUpsertBulk) UpdateCreatedAt() *SearchQueryUpsertBulk {
	return u.Update(func(s *SearchQueryUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *SearchQueryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SearchQueryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SearchQueryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SearchQueryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
